const data = [
  {
    mID: 1200,
    mValue: "CAR INSURANCE",
    mType: "BrokerProduct",
    mDataType: null,
    mParentDataType: null,
    mData: "/modules/BrokerPortal/Pages/MotorQuote",
    childName: "Car",
    parentId: 0,
    mTypeCode: "449",
    check: false,
    children: [
      {
        mID: 1220,
        mValue: "NewBusiness",
        mType: "BusinessType",
        mDataType: null,
        mParentDataType: null,
        mData: "",
        check: false,
        childName: "New Business",
        parentId: 1200,
        mTypeCode: "",
        children: [
          {
            mID: 1,
            mValue: "BusinessList",
            mType: "BusinessList",
            mDataType: null,
            mParentDataType: null,
            mData: null,
            childName: null,
            check: false,
            parentId: 0,
            mTypeCode: null,
            children: [
              {
                mID: 5,
                mValue: "BusinessList1",
                mType: "BusinessList",
                mDataType: null,
                mParentDataType: null,
                mData: null,
                childName: null,
                check: false,
                parentId: 0,
                mTypeCode: null,
                children: [],
              },
            ],
          },
          {
            mID: 10,
            mValue: "BusinessData",
            mType: "BusinessList",
            mDataType: null,
            mParentDataType: null,
            mData: null,
            check: false,
            childName: null,
            parentId: 0,
            mTypeCode: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    mID: 1201,
    mValue: "BIKE INSURANCE",
    mType: "BrokerProduct",
    mDataType: null,
    mParentDataType: null,
    mData: "/modules/BrokerPortal/Pages/Bike/BikeQuote",
    childName: "Bike",
    parentId: 0,
    mTypeCode: "449",
    children: [
      {
        mID: 1224,
        mValue: "New Business",
        mType: "BusinessType",
        mDataType: null,
        mParentDataType: null,
        mData: "",
        check: false,
        childName: null,
        parentId: 1201,
        mTypeCode: "",
        children: [
          {
            mID: 9,
            mValue: "BusinessList",
            mType: "BusinessList",
            mDataType: null,
            mParentDataType: null,
            mData: null,
            childName: null,
            check: false,
            parentId: 0,
            mTypeCode: null,
            children: [
              {
                mID: 1245,
                mValue: "Quote Generation",
                mType: "BusinessFlow",
                mDataType: null,
                mParentDataType: null,
                mData: "",
                childName: null,
                check: false,
                parentId: 0,
                mTypeCode: "",
                children: [],
              },
              {
                mID: 1246,
                mValue: "Proposal",
                mType: "BusinessFlow",
                mDataType: null,
                mParentDataType: null,
                mData: "",
                childName: null,
                check: false,
                parentId: 0,
                mTypeCode: "",
                children: [],
              },
              {
                mID: 1247,
                mValue: "Policy Issuance",
                mType: "BusinessFlow",
                mDataType: null,
                mParentDataType: null,
                check: false,
                mData: "",
                childName: null,
                parentId: 0,
                mTypeCode: "",
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
export default data;
