const data = {
  BusinessProfile: "",
  TransactionID: "",
  CkycStatus: "",
  CkycDetails: {},
  GCProductCode: "",
  GCProductName: "",
  ProductName: "",
  "Agent Id": "",
  DocumentDetails: [
    {
      DocName: "",
      DocId: 1,
      DocType: "",
      DocRemarks: "",
      DocFlag: false,
      DocExtension: "",
      DocDate: "",
      DMSDocId: "",
    },
  ],
  InsurableItem: [
    {
      InsurableName: "Building",
      RiskItems: [
        {
          id: 1,
          cancelFlag: false,
          Pincode: "",
          State: "",
          City: "",
          Address1: "",
          Address2: "",
          GSTNo: "",
          Total: "",
          TariffZone: "",
          SumInsuredBifurcation: [
            {
              RiskType: "Building",
              SI: "",
            },
            {
              RiskType: "Plant and Machinery",
              SI: "",
            },
            {
              RiskType: "Furniture Fixture and Fittings",
              SI: "",
            },
            {
              RiskType: "Other Content",
              SI: "",
            },
            {
              RiskType: "Raw Material",
              SI: "",
            },
            {
              RiskType: "Stock in Progress",
              SI: "",
            },
            {
              RiskType: "Finished Stock",
              SI: "",
            },
            {
              RiskType: "Other Contents Please Specify",
              SI: "",
            },
          ],
        },
      ],
      Covers: [
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
      ],
    },
    {
      InsurableName: "Contents",
      RiskItems: [{}],
      Covers: [
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
        {
          CoverName: "",
          CoverFields: [{}],
        },
      ],
    },
  ],
  PartnerID: "",
  "Product Code": "BLUS_BSUS",
  DocumentUpload: "yes",
  SIFloaterforStock: "",
  FloaterforStock: "No",
  FinancierAddress: "",
  DeclarationforStock: "No",
  HypothecationFinancierName: "",
  CorporateName: "",
  Distancefrompublicfirebrigade: "",
  StockExposure: "",
  RiskTerrain: "",
  ClaimsRatio: "",
  HousekeepingType: "",
  AgeofBuilding: "",
  ClaimExperience: "",
  BasementExposure: "",
  PastFlooding: "",
  InsuredMobileNo: "",
  TotalSumInsuredProposed: "",
  Occupancy: "",
  OccupancyType: "",
  OccupancyWarrenty: "",
  TransactionType: "New Business",
  Location: "",
  SubProduct: "",
  ClientsBusinessExperience: "",
  TypeofConstruction: "",
  Loading: "",
  CustomerType: "Individual",
  EESumInsured: "",
  ExpenseInsurance: "",
  ClearingDrains: "",
  CDSumInsured: "",
  POPSumInsured: "",
  PreservationofProperty: "",
  includeForeignDebris: "",
  ARODSumInsured: "",
  AdditionalRemovalofDebris: "",
  IBCSumInsured: "",
  InvoluntaryBettermentCover: "",
  ECSumInsured: "",
  EscalationClause: "",
  LORSumInsured: "",
  LossofRent: "",
  ADSumInsured: "",
  AccidentalDamageCover: "",
  OptAddonCovers: "",
  FireProtection: "",
  Lossofrent: "",
  OtherCovers: {
    "Extra Expenses": "",
    "Cost of Clearing Drains": "",
    "Protection and Preservation": "",
    "Additional Removal Debris": "",
    "Involuntary Betterment": "",
    "Escalation Clause": "",
    "Loss of Rent": "",
    "Accidental Damage": "",
  },
  ProposerDetails: {
    PolicyStartDate: "",
    PolicyEndDate: "",
    Salutation: "",
    ProposerName: "",
    "First Name": "",
    "Middle Name": "",
    "Last Name": "",
    "Email ID": "",
    "Mobile Number": "",
    Name: "",
    PinCode: "",
    District: "",
    State: "",
    DOB: "",
    Age: "",
    Gender: "",
    EmailId: "",
    MobileNo: "",
    PAN: "",
    GST: "",
    CIN: "",
    CKYCParam: "",
    AadharID: "",
    AadharMobileNo: "",
    AadharName: "",
    AadharGender: "",
    GSTLocation: "",
    Nationality: "",
    VIPFlag: "",
    eIANoYN: "",
    eIANo: "",
    UniqueIdentificationNoYN: "",
    UniqueIdentificationNumber: "",
    EmployeeID: "12345678",
    PermanentAddress: {
      AddressLine1: "",
      AddressLine2: "",
      Pincode: "",
      Area: "",
      CityDistrict: "",
      State: "",
    },
    CommunicationSameasPermanentYN: "",
    CommunicationAddress: {
      AddressLine1: "",
      AddressLine2: "",
      Pincode: "",
      Area: "",
      CityDistrict: "",
      State: "",
    },
  },
  OtherDetails: {
    CustomerContactNumber: "",
    CustomerEmailID: "",
    GSTIN: "",
    PAN: "",
  },
  PremiumDetails: {
    "Long term": 0,
    "Net Premium": 0,
    SGST: 0,
    CGST: 0,
    "Total with Tax": 0,
    TotalTerrorismPremium: "",
    TotalPremiumExcTerrorism: "",
    TotalFirePremium: "",
    AdditionalPremiumDetails: [
      {
        TerrorismPremium: 0,
        EarthquakePremium: 0,
        STFIPremium: 0,
        BaseFirePremium: 0,
        STFIDiscountedRate: 0,
        BaseDiscountedRate: 0,
        EQDiscountedRate: 0,
        TerrorismDiscountedRate: 0,
        PremiumExcTerrorism: 0,
        TotalAddOnPremium: 0,
        "Net Premium": 0,
        SGST: 0,
        CGST: 0,
        "Total with Tax": 0,
        GCBasewithLoadingPremium: 0,
      },
    ],
  },
  PaymentDetails: {
    ChequeAmount: "",
    InstrumentNo: "",
    InstrumentDate: "",
    BankName: "",
    transactionNo: "",
    paymentSource: "",
    paymentId: "",
    paymentResponse: "",
    paymentType: "Agent Payment",
  },
  PolicyTenure: "",
  Channel: {
    BranchCode: "",
    BranchLocation: "",
    AgentID: "",
    AgentName: "",
    AgentType: "",
    AgentContactNo: "",
    Salespersoncode: "",
    Salespersonname: "",
    ChannelType: "Agency",
    OfficeCode: "",
    OfficeName: "",
    OfficeAddress: "",
    PrimaryMOCode: "",
    PrimaryMOName: "",
    PrimaryVerticalCode: "",
    PrimaryVerticalName: "",
    DealId: "",
  },
  LOB: "Fire",
  "Quotation No": "",
  QuoteMobileNo: "",
  QuoteEmail: "",
};

export default data;
