const getJson = () => {
  const json = {
    isValid: true,
    claimNumber: "",
    claimVersion: 0,
    claimStatusId: 0,
    createdDate: "",
    modifiedDate: "",
    createdBy: "",
    modifiedBy: "",
    fnol: "",
    policyDetailsId: 0,
    countryId: 0,
    stateId: 0,
    policyNo: "",
    districtId: 0,
    cityId: 0,
    areaId: 0,
    intimationModeId: 0,
    intimationById: 0,
    incidentDateTime: "",
    incidentLocation: "",
    isFir: true,
    firdateTime: "",
    nameOfPoliceStation: "",
    isAnyWitness: true,
    isAnyOtherVehicleInAccident: true,
    driverOfTheVehicleId: 0,
    driverName: "",
    driverLicenseNo: "",
    driverLicenseExpiryDateTime: "",
    rtodetailId: 0,
    dlauthorizedToDriveId: 0,
    roadTypeId: 0,
    purposeOfTravelId: 0,
    isVehicleParked: true,
    vehicleSpeed: 0,
    numberOfPasanger: 0,
    weatherCondition: "",
    firno: "",
    driverAge: 0,
    drivingExperience: 0,
    driverQualificationId: 0,
    driverDob: "",
    fathersName: "",
    isTrailerAttached: true,
    registeredLadenWeightKg: 0,
    registeredUnLadenWeightKg: 0,
    weightOfGoodsCarriedKg: 0,
    typeOfGoodsCarried: "",
    natureOfGoodsCarried: "",
    registeredPassengerCarryingCapacity: 0,
    passengersCarried: 0,
    natureOfPermit: "",
    typeOfPermit: "",
    permitValidForAreas: "",
    permitValidUpTo: "",
    fitnessValidUpTo: "",
    mobileNumber: "",
    email: "",
    partnerId: 0,
    productId: 0,
    eventId: "",
    claimBasicDetails: "",
    basicDetails: {
      claimId: 0,
      claimNo: "",
      uhid: "",
      policyType: "",
      productCode: "",
      policyInceptionDate: "",
      policyDetails: {
        policyNumber: "",
        policyStartDate: "",
        policyEndDate: "",
        tripType: "",
        geography: "",
      },
      claimDetails: {
        travelStartDate: "",
        travelStartTime: "",
        travelEndDate: "",
        travelEndTime: "",
      },
      memberDetails: {
        memberId: "",
        insuredName: "",
        gender: "",
        insuredAge: 0,
        patientRelationship: "",
        memberAttachmentDate: "",
        employeeId: 0,
        employeeName: "",
      },
      nomineeDetails: {
        nomineeDOB: "",
        nomineeName: "",
        relationWithInsured: "",
        address1: "",
        address2: "",
        address3: "",
        nomineeCity: "",
        nomineeEmailID: "",
        nomineeMobile: "",
        nomineePincode: "",
        nomineeState: "",
      },
    },
    claimTransactionDTO: [
      {
        transactionId: 0,
        transactionNumber: "",
        isValid: true,
        createdDateTime: "",
        modifiedDateTime: "",
        createdBy: "",
        modifiedBy: "",
        occurrence: "",
        claimId: 0,
        statusId: 0,
        status: "",
        claimTypeId: 0,
        claimServiceTypeId: 0,
        causeOfLossId: 0,
        actionId: 0,
        isServeyorAssign: true,
        isWorkshopAssign: true,
        isInvestigatorAssign: true,
        isBackByManager: true,
        isReOpen: true,
        isRoadSideAssistance: true,
        approximateEstimatedCost: 0,
        remark: "",
        internalRemark: "",
        emergencyContact: "",
        emergencyEmail: "",
        queryReasonIds: "",
        rejectionReasonIds: "",
        accidentFactor: "",
        accidentFactorDescription: "",
        isRead: true,
        approvedAmount: 0,
        decisionTypeid: 0,
        settlementTypeid: 0,
        closeReasonIds: "",
        isPriorityClaim: true,
        reopenReasonIds: "",
        advanceAmount: 0,
        claimNo: "",
        workItemNo: "",
        workItemId: 0,
        userName: "",
        transactionDetails: "",
        transactionDetailsDto: {
          claimCategory: "",
          claimSubType: "",
          inwardNo: "",
          inwardDateTime: "",
          natureOfClaim: "",
          causeOfLoss: "",
          benefitName: "",
          typeOfLoss: "",
          reasonofLoss: "",
          country: "",
          placeOfLoss: "",
          claimantContactName: "",
          claimantContactNo: "",
          claimantEmail: "",
          remarks: "",
          doaDol: "",
          doaDolTime: "",
          dod: "",
          dodTime: "",
          waitingPeriod: "",
          noOfDays: "",
          noOfHours: "",
          modifiedDateTime: "",
          isTpa: true,
          isDocCorrect: "",
          docDate: "",
          hospitalDetails: {
            hospitalName: "",
            hospitalCountry: "",
            hospitalState: "",
            pincode: "",
            hospitalDistrict: "",
            hospitalAddress: "",
            isNetwork: true,
            hospitalInvoiceDate: "",
            contactNo: "",
            faxNo: "",
            emailId: "",
          },
          courierDetails: {
            physicalDocsReceived: "",
            isTypeOfCourier: "",
            isClaimReceivedAtBranch: true,
            isClaimReceivedAtHo: true,
            sentDateTime: "",
            courierNameBranch: "",
            courierNameHo: "",
            podBranch: "",
            podHo: "",
            walkindt: "",
            customertName: "",
            contactNo: "",
          },
          benefitDetails: [
            {
              benefit: "",
              claimedAmount: "",
              claimValue: "",
              calculatedClaimAmount: "",
              approvedClaimAmount: "",
              isValid: true,
              isLumpSum: "",
              isBreakup: "",
              createdDateTime: "",
              deductible: "",
              additionalDeductible: 0,
              remarks: "",
              billing: [
                {
                  billNo: "",
                  billDate: "",
                  billDiscount: 0,
                },
              ],
              billingDetails: [
                {
                  billNo: "",
                  quantity: "",
                  category: "",
                  billDescription: "",
                  rate: "",
                  estimatedAmount: "",
                  approvedAmount: "",
                  deduction: "",
                  remarks: "",
                },
              ],
            },
          ],
          paymentObj: {
            approvedAmount: "",
            isApprovedAmountCorrect: true,
            work: true,
            customer: true,
            a1: true,
            a2: true,
            paymentDetails: [
              {
                payeeName: "",
                accountType: "",
                accountNumber: "",
                panNo: "",
                ifscCode: "",
                amountType: "",
                amount: "",
                bankName: "",
                bankBranchAddress: "",
                payeeType: "",
                currMasFrom: "",
                currMasTo: "",
                excRate: "",
                calAmt: "",
              },
            ],
            action: "",
            remarks: "",
          },
          documentDetails: [
            // {
            //   docId: "",
            //   docName: "",
            //   docType: "",
            //   docTypeName: "",
            //   uploadDocDate: "",
            //   contentType: "",
            // },
          ],
          tpaDetails: {
            name: "",
            registrationNo: "",
            nameOfCAOCEO: "",
            contactNo: "",
            email: "",
          },
        },
      },
    ],
  };
  // const json = {
  //   claimId: 0,
  //   claimStatusId: 0,
  //   claimNumber: "",
  //   claimAmount: 0,
  //   claimManagerRemarks: "",
  //   approvedClaimAmount: 0,
  //   createdDate: "",
  //   createdBy: "",
  //   lossId: 0,
  //   lossDateTime: "",
  //   locationOfEvent: "",
  //   lossOfDescription: "",
  //   policyId: 0,
  //   active: true,
  //   modifiedBy: "",
  //   modifiedDate: "",
  //   partnerId: 0,
  //   organizationId: 0,
  //   policyNo: "",
  //   productIdPk: 0,
  //   claimFields: "",
  //   company: "",
  //   lob: "",
  //   claimBasicDetails: {
  //     claimId: 0,
  //     claimNo: "",
  //     workItemType: "",
  //     uhid: "",
  //     policyType: "",
  //     productCode: "",
  //     policyInceptionDate: "",
  //     policyDetails: {
  //       policyNumber: "",
  //       customerId: "",
  //       policyStartDate: "",
  //       policyEndDate: "",
  //       tripType: "",
  //       geography: "",
  //     },
  //     claimDetails: {
  //       travelStartDate: "",
  //       travelStartTime: "",
  //       travelEndDate: "",
  //       travelEndTime: "",
  //     },
  //     memberDetails: {
  //       memberId: "",
  //       insuredName: "",
  //       gender: "",
  //       insuredAge: 0,
  //       patientRelationship: "",
  //       memberAttachmentDate: "",
  //       employeeId: 0,
  //       employeeName: "",
  //     },
  //     nomineeDetails: {
  //       nomineeDOB: "",
  //       nomineeName: "",
  //       relationWithInsured: "",
  //       address1: "",
  //       address2: "",
  //       address3: "",
  //       nomineeCity: "",
  //       nomineeEmailID: "",
  //       nomineeMobile: "",
  //       nomineePincode: "",
  //       nomineeState: "",
  //     },
  //   },
  //   claimVersion: 1,
  //   transactionDataDTO: [],
  // };
  return json;
};

const getAccordianList = (flag) => {
  const accordians = [
    { accname: "Member Details", visible: !flag },
    { accname: "Policy Details", visible: !flag },
    { accname: "Claim Details", visible: !flag },
    { accname: "Hospital Details", visible: !flag },
    { accname: "Nominee Details", visible: !flag },
    { accname: "Document Details", visible: !flag },
  ];
  return accordians;
};

function getAccordianContents(x, ClaimJson, policyData) {
  let data = [];
  switch (x) {
    case "Member Details":
      data = [
        {
          type: "DataGrid",
          spacing: 12,
          columns: [
            { field: "memberId", headerName: "Member ID", width: 200 },
            { field: "memberName", headerName: "Member Name", width: 200 },
            { field: "claimType", headerName: "Claim Type", width: 200 },
          ],
          rows: [],
          rowId: "memberId",
          visible: true,
          // onRowClick:
        },
      ];
      break;
    case "Policy Details":
      data = [
        {
          type: "Input",
          label: "Policy Number",
          name: "policyNo",
          value: policyData.PolicyNumber,
          visible: true,
          InputProps: { readOnly: true },
          set: policyData.PolicyNumber,
          setTo: ClaimJson.policyNo,
        },
        {
          type: "Input",
          label: "Policy Start Date",
          name: "policyStartDate",
          value: policyData.PolicyStartDate,
          visible: true,
          InputProps: { readOnly: true },
        },
        {
          type: "Input",
          label: "Policy End Date",
          name: "policyEndDate",
          value: policyData.PolicyEndDate,
          visible: true,
          InputProps: { readOnly: true },
        },
        {
          type: "Input",
          label: "Trip Type",
          name: "tripType",
          value: policyData.TripType,
          visible: true,
          InputProps: { readOnly: true },
        },
        {
          type: "Input",
          label: "Geography",
          name: "geography",
          value: policyData.Geography,
          visible: true,
          InputProps: { readOnly: true },
        },
      ];
      break;
    case "Claim Details":
      data = [
        {
          type: "AutoComplete",
          label: "Claim Category",
          visible: true,
          name: "claimCategory",
          // value: claimDetails.transactionDataDTO[0].transactionDetails.benefitDetails.benefit,
          // path: "benefitDetails",
          option: [],
        },
        {
          type: "DateTime",
          label: "Travel Start Date",
          visible: true,
          name: "travelStartDate",
          // value: policyData.PolicyStartDate,
          path: "hospitalizationDetails",
          InputProps: { readOnly: true },
        },
        {
          type: "DateTime",
          label: "Travel End Date",
          visible: true,
          name: "travelEndDate",
          // value: policyData.PolicyStartDate,
          path: "hospitalizationDetails",
          InputProps: { readOnly: true },
        },
        {
          type: "AutoComplete",
          label: "Select Cause of Loss",
          visible: true,
          name: "causeOfLoss",
          // value: claimDetails.transactionDataDTO[0].transactionDetails.benefitDetails.benefit,
          // path: "benefitDetails",
          option: [],
        },
        {
          type: "Input",
          label: "Reason of Loss",
          name: "reasonOfLoss",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "AutoComplete",
          label: "Country",
          visible: true,
          name: "country",
          // value: claimDetails.transactionDataDTO[0].transactionDetails.benefitDetails.benefit,
          // path: "benefitDetails",
          option: [],
        },
        {
          type: "Input",
          label: "Place of Loss",
          name: "placeOfLoss",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Claimant Name",
          name: "claimantName",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Claimant Contact Number",
          name: "contactNumber",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Claimant Email",
          name: "email",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "DateTime",
          label: "DOA/DOD",
          visible: true,
          name: "doadol",
          // value: policyData.PolicyStartDate,
          // path: "hospitalizationDetails",
          InputProps: { readOnly: true },
        },
        {
          type: "Input",
          label: "Remarks",
          name: "remarks",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
      ];
      break;
    case "Hospital Details":
      data = [
        {
          type: "Input",
          label: "Name of Hospital",
          name: "hospitalName",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Address",
          name: "address",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "City",
          name: "city",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "State",
          name: "state",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Pincode/Zipcode",
          name: "pincode",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Country",
          name: "country",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Hospital Contact Number",
          name: "hospitalContactNumber",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Hospital Fax Number",
          name: "hospitalFaxNumber",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Hospital Email ID",
          name: "emailId",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "DateTime",
          label: "Hospital Invoice Date",
          visible: true,
          name: "hospitalInvpoiceDate",
          // value: policyData.PolicyStartDate,
          // path: "hospitalizationDetails",
          InputProps: { readOnly: true },
        },
      ];
      break;
    case "Nominee Details":
      data = [
        {
          type: "Input",
          label: "Nominee Name",
          name: "nomineeName",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "DateTime",
          label: "Nominee DOB",
          visible: true,
          name: "dob",
          // value: policyData.PolicyStartDate,
          // path: "hospitalizationDetails",
          InputProps: { readOnly: true },
        },
        {
          type: "Input",
          label: "Relation with Insured",
          name: "relationWithInsured",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Nominee EmailID",
          name: "nomineeEmail",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Nominee Mobile",
          name: "nomineeMobile",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Nominee Pincode",
          name: "nomineePincode",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Nominee State",
          name: "nomineeState",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Nominee City",
          name: "nomineeCity",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Nominee Address1",
          name: "nomineeAddress1",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Nominee Address2",
          name: "nomineeAddress2",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
        {
          type: "Input",
          label: "Nominee Address3",
          name: "nomineeAddress3",
          // value: ClaimsJson.transactionDataDTO[0].transactionDetails.hospitalDetails.hospitalName,
          visible: true,
          // path: "hospitalDetails",
        },
      ];
      break;
    default:
      data = [];
      break;
  }
  return data;
}

export { getJson, getAccordianList, getAccordianContents };
