const data = {
  UserName: "",
  AgentCode: "",
  BranchName: "",
  ProductId: "872",
  ProfileNumber: "",
  BranchCode: "",
  BOV: "",
  TypeOfPolicy: [],
  CargoType: [],
  BasisOfValuation: [],
  Risk: [],
  AdditionalCondition: "",
  FromCountry: [],
  ToCountry: [],
  SpecialConditionExclusion: "",
  MaximumSumInsured: "",
  MinimumRate: "",
  MinimumPremium: "",
  Markup: "",
  Excess: "",
  BackDate: "",
  clauses: [
    {
      "Marine Specific Voyage Import": {
        air: {
          CommonClauses: [],
          NonInstituteClauses: [],
          InstituteClauses: [],
        },
        sea: { CommonClauses: [], NonInstituteClauses: [], InstituteClauses: [] },
        Courier: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        ParcelPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        InlandRailRoadAir: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        RegisteredPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        Others: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
      },
      "Marine Specific Voyage Export": {
        air: { CommonClauses: [], NonInstituteClauses: [], InstituteClauses: [] },
        sea: { CommonClauses: [], NonInstituteClauses: [], InstituteClauses: [] },
        Courier: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        ParcelPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        InlandRailRoadAir: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        RegisteredPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        Others: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
      },

      "Marine Specific Voyage Export FOB": {
        air: { CommonClauses: [], NonInstituteClauses: [], InstituteClauses: [] },
        sea: { CommonClauses: [], NonInstituteClauses: [], InstituteClauses: [] },
        Courier: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        ParcelPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        InlandRailRoadAir: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        RegisteredPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        Others: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
      },
      "Marine Specific Voyage Inland": {
        air: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        sea: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        Courier: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        InlandRailRoadAir: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        ParcelPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        RegisteredPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        Others: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
      },
      "Marine Specifc Voyage Duty": {
        air: { CommonClauses: [], NonInstituteClauses: [], InstituteClauses: [] },
        sea: { CommonClauses: [], NonInstituteClauses: [], InstituteClauses: [] },
        Courier: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        InlandRailRoadAir: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        ParcelPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        RegisteredPost: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
        Others: { CommonClauses: [], NonInstituteClauses: [], InlandTransitClauses: [] },
      },
    },
  ],
};

export default data;
