const PolicyDto = () => ({
  ProposalDate: "",
  proposalNo: "",

  policyNo: "",
  PolicyStartTime: "",
  PolicyEndTime: "",
  PolicyStartDate: "",
  PolicyEndDate: "",
  Plan: "",
  Scheme: "",
  CoverType: "test1",
  CustomerId: "",
  CountofLives: "",
  PolicyType: "Floater",
  ChildCount: "",
  InstallmentFrequency: "",
  NoOfInstallment: "",
  NOOfDays: "19",

  PolicyTenure: 1,
  SumInsured: "",
  PaymentDetails: {
    TransactionNo: "",
    Amount: "",
    PaymentGateway: "",
    PaymentStatus: "",
    EmailId: "",
    TransactionType: "",
    Description: "",
    ModeOfPayment: "",
    DocumentType: "",
    BRANCH_GSTIN: "",
    CUSTOMER_GSTIN: "",
    MAXBUPA_BRANCH_CODE: "",
    CUSTOMER_STATE_CODE: "",
  },
  PartnerDetails: {
    accountNo: "",
    description: "The Amount is Deducted",
    isRefund: true,
    orgId: 0,
    partnerCode: "",
    paymentId: 0,
    txnAmount: 180,
    txnId: 0,
    txnType: "Debit",
    GSTNumber: "09AAFCM7916H1Z6",

    partnerName: "",
    masterPolicyNo: "",
    PolicyStartTime: "",
    PolicyEndDate: "",
    website: "",
    address1: "",
    address2: "",
    city: "",
    district: "",
    state: "",
    country: "",
    pincode: "",
  },

  Benefits: [],
  "Total Count": "",
  ProductCode: "AmanaTakaful02",
  Channel: {
    BranchCode: "",
    BranchLocation: "",
    AgentID: "",
    AgentName: "",
    Salespersoncode: "",
    Salespersonname: "",
    ChannelType: "",
  },
  ProposerDetails: {
    CommunicationAddress: {
      AddressLine1: "",
      AddressLine2: "",
      AddressLine3: "",
      Landmark: "",
      CityDistrict: "",
      State: "",
      StateCode: "",
      Country: "",
      Pincode: "",
    },
    PermanentAddress: {
      AddressLine1: "",
      AddressLine2: "",
      AddressLine3: "",
      City: "",
      District: "",
      State: "",
      Country: "",
      Pincode: "",
    },
    Name: "",
    MobileNo: "",
    Nationality: "",
    Salutation: "",
    EmailId: "",
    DOB: "",
    Age: "",
    Gender: "",
    MaritalStatus: "",
    OccupationCode: "",
    PanNo: "",
    AnnualIncome: "",
    GSTNumber: "",
    AadharCard: "",
    AlternateMobileNo: "",
    RelationWithInsured: "",
    RuralAndSocialSectorCategory: "",
    CKYCNo: "",
  },
  InsurableItem: [
    {
      InsurableName: "Person",
      Covers: [
        {
          CoverName: "Hospicash - Normal Admission",
          selected: true,
        },
      ],
      RiskItems: [],
    },
  ],
  NomineeDetails: [
    {
      NomineeName: "",
      NomineeDOB: "",
      NomineeAge: 20,
      NomineeRelationWithProposer: "",
      PercentageOfShare: "",
      GuardianName: "",
      GuardianDOB: "",
      RelationWithInsured: "",
      NomineeAddressLine1: "",
      NomineeAddressLine2: "",
      NomineeAddressLine3: "",
      NomineeMobile: "",
      NomineeEmailID: "",
      AppointeeName: "",
      AppointeeDOB: "",
      AppointeeRelationWithProposer: "",
      NomineeCity: "",
      NomineeState: "",
      NomineePincode: "",
    },
  ],
  PremiumDetails: {
    netPremium: "",
    gst: "",
    totalPremium: "",
  },
});

const RiskItem = () => ({
  Name: "",
  DOB: "",
  Age: "",
  Gender: "",
  DOJ: "",
  DOC: "",
  Grade: "",
  Designation: "",
  EmailID: "",
  NoOfLives: "1",
  Remarks: "",
  PassportNo: "",
  PreExistingDisease: "",
  Nationality: "",
  SumInsured: "",
  Plan: "",
  HeightMember: "",
  WeightMember: "",
  MobileNumber: "",
  Relationship: "",
});

const relationShip = [
  { mID: 1, mValue: "Self" },
  { mID: 2, mValue: "Spouse" },
  { mID: 3, mValue: "Son" },
  { mID: 4, mValue: "Daughter" },
  { mID: 5, mValue: "Father" },
  { mID: 6, mValue: "Mother" },
  { mID: 7, mValue: "Child" },
];

const Gender = [
  { mID: 1, mValue: "Male" },
  { mID: 2, mValue: "Female" },
];

export { PolicyDto, RiskItem, relationShip, Gender };
