const data = {
  SubProduct: "",
  GCProductCode: "",
  GCProductName: "",
  GCTransportType: "",
  "Policy Tenure": 0,
  "Agent Id": "",
  ProfileType: "",
  BranchName: "",
  BranchCode: "",
  "Type of Policy": "",
  "LC No.": "",
  "Sum Insured in Currency of Invoice": "",
  "Sum Insured in INR ": "",
  "Sum Insured including Markup": "",
  "Sum Insured in INR for Duty ": "",
  "Exchange Rate": "",
  Rate: "",
  PropRisks_Ratevalue: "",
  "Other Description ": "",
  "Markup %": "",
  "Net Premium": 0,
  "Stamp Duty": 0,
  "Total Premium": 0,
  "Special LC Condition/Remarks": "",
  "Basis of Valuation Percentage": "10",
  "Consigner Name & Address": "",
  Remarks: "",
  "Consignee Name & Address": "",
  ClaimRatio: "0",
  "Invoice Date": "",
  "Invoice No": "",
  Deductible: 0,
  "ST/GST": 0,
  QuoteEmail: "",
  QuoteMobileNo: "",
  "Basis of Valuation": "",
  "Risk Type": "",
  "No. of Weeks": "0",
  "Own Share PSL": "",
  "Route Details": "",
  "Port of Discharge": "",
  "Port of Loading": "",
  "Port of Loading1": "",
  "Port of Discharge1": "",
  "City To": "",
  "City From": "",
  "Type Mark & Container No.": "",
  "Survey Agent": "",
  "Claim Ratio": "0",
  "Flag of Convenience": "",
  "Transit To": "",
  "Transit From": "",
  "BL/AWB/LR/RR No": "",
  "Voyage No": "",
  "TPND Cover Required": "",
  "Intermediary Coverage ": "",
  "Intermediary Storage Location": "",
  "Intermediary Storage Required ": "",
  "Cover Type": "",
  CoverTypemValue: "",
  "Settling Agent": "",
  "Settling Agent Country": "",
  "Vessel Description ": "",
  "Vessel Name": "",
  "Weight of Goods": "",
  "Total Packages": "",
  "Currency of Invoice": "",
  "Other Description": "",
  "Description of Cargo": "",
  CkycStatus: "",
  CkycDetails: {},
  ProposerDetails: {
    Salutation: "",
    "Customer Type": "Individual",
    Name: "",
    "First Name": "",
    "Last Name": "",
    "Date of Birth": "",
    Gender: "",
    "Mobile Number": "",
    "Email ID": "",
    termscondition: true,
    autoFill: "",
    Age: "",
    PinCode: "",
    DistrictCode: "",
    StateCode: "",
    Area: "",
    District: "",
    State: "",
    EnhancedSumAssured: "",
    NomineeRelation: "",
    NomineeName: "",
    SumInsured: "",
    Address: "",
    "Address 1": "",
    "Address 2": "",
    "Nearest Landmark": "",
    Country: "INDIA",
    PAN: "",
    GSTIN: "",
    CIN: "",
    CKYCParam: "",
    AadharID: "",
    AadharMobileNo: "",
    AadharName: "",
    AadharGender: "",
    "Policy Tenure": 0,
    OtherRelation: "",
    ProductId: "",
    "Other Sum Insured": "",
    "Financer Name": "",
    undefined: false,
    "Policy Start Date": "",
    "Policy End Date": "",
    GCPolicyStartDate: "",
  },
  PremiumDetails: {
    CollectedCGST: 0,
    CollectedIGST: 0,
    CollectedSGST: 0,
    GST: 0,
    InvoicevalueINR: 0,
    PremiumExcludingGST: 0,
    PremiumIncludingGST: 0,
    Stampduty: 0,
    SumInsuredinINR: 0,
    TotalCargoSI: 0,
  },

  "Product Code": "MarineSpecificVoyage",
  permiumamount: "",
  InsurableItem: [
    {
      InsurableName: "Cargo",
      RiskItems: [
        {
          "Markup %": "",
          "Basis of Valuation Percentage": "10",
          "Category of Vessel": "",
          "Type Mark & Container No.": "",
          "Age of Vessel": "",
          "Vessel Description": "",
          "Transport Type": "",
          "Vessel Name": "",
          "Weight of Goods": "",
          "Total Packages": "",
          ExcellentPacking: "Yes",
          Packing: "",
          "Is Cargo Carried in FCL": "",
          "Is Cargo Containerized": "No",
          "Cargo on Deck": "No",
          "Description of Cargo": "",
          Cargo: "",
          "Type of Cargo": "Bulk",
          "GRT (Gross Registered Tonnage)": "",
        },
      ],
      Covers: [
        {
          CoverName: "Institute Cargo Clauses ( C ) ",
          CoverFields: [{}],
        },
        {
          CoverName: "Institute Cargo Clauses (B) ",
          CoverFields: [{}],
        },
        {
          CoverName: "Institute Cargo Clauses (A) ",
          CoverFields: [{}],
        },
      ],
    },
  ],
  PaymentDetails: {
    ChequeAmount: "",
    InstrumentNo: "",
    InstrumentDate: "",
    BankName: "",
    transactionNo: "",
    paymentSource: "Client Payment",
    paymentId: "",
    paymentResponse: "",
  },
  Channel: {
    BranchCode: "",
    BranchLocation: "",
    AgentID: "",
    AgentName: "",
    AgentType: "",
    AgentContactNo: "",
    Salespersoncode: "",
    Salespersonname: "",
    ChannelType: "Agency",
    OfficeCode: "",
    OfficeName: "",
    OfficeAddress: "",
    PrimaryMOCode: "",
    PrimaryMOName: "",
    PrimaryVerticalCode: "",
    PrimaryVerticalName: "",
  },
  clauses: [],
  ClausesWarrantyExclusionsExcess: [],
  RiskClauses: [],
};

export default data;
