function PolicyJson() {
  return {
    QuotationList: [],
    ProposalData: [],
    ProposerDetails: {
      DOB: "",
      PanNo: "",

      FirstName: "",

      LastName: "",

      PermanentAddress: {
        AddressLine1: "",
        AddressLine2: "",
        CityDistrict: "",
        State: "",
        Pincode: "",
      },
    },
    QuotationData: [],
    RiskItems: [
      {
        Name: "1",
        Questionnare: [
          //   {
          //     LevelNo: 100000000,
          //     QId: 1,
          //     QText: "Are you, or have you been (If yes to any of below please provide details)",
          //     ControlType: "Header",
          //     OnChangeVal: "",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 101000000,
          //     QId: 2,
          //     QText:
          //       "a) In close contact with anyone who has been quarantined or who has been diagnosed with novel coronavirus (SARS-CoV-2/COVID-19)?",
          //     QParentId: 1,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 102000000,
          //     QId: 3,
          //     QText:
          //       "b) Quarantined due to a possible exposure to novel coronavirus (SARSCoV2/COVID-19)?",
          //     QParentId: 1,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 103000000,
          //     QId: 4,
          //     QText: "c) Tested positive for the novel coronavirus or await the result of such test?",
          //     QParentId: 1,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 104000000,
          //     QId: 5,
          //     QText:
          //       "d) Advised to be tested to rule in, or rule out, a diagnosis of novel coronavirus?",
          //     QParentId: 1,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 200000000,
          //     QId: 6,
          //     QText: "Have you experienced any of the following symptoms within the last 14 days?",
          //     ControlType: "Header",
          //     OnChangeVal: "",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 201000000,
          //     QId: 7,
          //     QText: "a) Any fever //Cough//Shortness of breath //Malaise (flu-like tiredness)",
          //     QParentId: 6,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 202000000,
          //     QId: 8,
          //     QText: "b) Rhinorrhea (mucus discharge from the nose) //Sore throat",
          //     QParentId: 6,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 203000000,
          //     QId: 9,
          //     QText: "c) Gastro-intestinal symptoms such as nausea, vomiting and/or diarrhea",
          //     QParentId: 6,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 300000000,
          //     QId: 10,
          //     QText:
          //       "Please provide your travel patterns over the past 14 days/ next 30 days (provide details if Yes)",
          //     ControlType: "TextBox",
          //     OnChangeVal: "",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 400000000,
          //     QId: 11,
          //     QText: "Are you currently in good Health?",
          //     DefaultValue: "Yes",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "No",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 500000000,
          //     QId: 12,
          //     QText:
          //       "Does your occupation fall within any of the below mentioned? (If yes please provide details)",
          //     ControlType: "Header",
          //     OnChangeVal: "",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 501000000,
          //     QId: 13,
          //     QText: "a) Doctor/ medical professional",
          //     QParentId: 12,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 502000000,
          //     QId: 14,
          //     QText: "b) Nursing personnel",
          //     QParentId: 12,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 503000000,
          //     QId: 15,
          //     QText: "c) Pharmacist",
          //     QParentId: 12,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 504000000,
          //     QId: 16,
          //     QText: "d) Transport work force personnel",
          //     QParentId: 12,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 505000000,
          //     QId: 17,
          //     QText: "e) Police/Military staff",
          //     QParentId: 12,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 506000000,
          //     QId: 18,
          //     QText: "e) Pilots/ Cabin Crew personnel",
          //     QParentId: 12,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 507000000,
          //     QId: 19,
          //     QText:
          //       "Any other occupation which has higher exposure to a large population. If yes, please",
          //     QParentId: 12,
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 600000000,
          //     QId: 20,
          //     QText:
          //       "Do you have any history of conviction under any criminal proceedings, in India or abroad?",
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 700000000,
          //     QId: 21,
          //     QText:
          //       "Is your occupation associated with any specific hazards which would render you susceptible to any injury or illness, (e.g.chemical factory, mines, explosives, corrosive chemicals, etc.?)",
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 800000000,
          //     QId: 22,
          //     QText:
          //       "Has your weight altered (Gain/Loss) by more than 5 kg in the last 1 year? If yes details required",
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
          //   {
          //     LevelNo: 900000000,
          //     QId: 23,
          //     QText:
          //       "Have you ever or are you currently suffering from any other illness, impairment or disability or any surgery not mentioned in the application form?",
          //     DefaultValue: "No",
          //     ControlType: "Radio",
          //     MasterType: "BooleanValue",
          //     OnChangeVal: "",
          //     ShowDetailsOnValue: "Yes",
          //     DetailsLabel: "Specify",
          //     Visibility: "true",
          //   },
        ],
        DocumentDetails: [
          // {
          //   "DocumentId":
          //   "23"
          //   "DocumentType":
          //   "Self attested copy of PAN card (only PDF format) "
          //   "IsMandatory":
          //   "true"
          //   },
          // {
          //   RowNum: 1,
          //   DocumentName:
          //     "Self attested copy of any one Address Proof (Only PDF format)-(Click to see the list of eligible documents)",
          //   IsMandatory: "true",
          // },
          // {
          //   RowNum: 2,
          //   DocumentName: "Utility Bill",
          //   IsMandatory: "true",
          // },
        ],
        comAddress: {
          address1: "",
          address2: "",
          address3: "",
          country: "",
          state: "",
          district: "",
          city: "",
          pincode: "",
        },
        ForeignAddress: {
          OCI: "",
          AddressLine1: "",
          AddressLine2: "",
          AddressLine3: "",
          City: "",
          District: "",
          State: "",
          Country: "",
          Pincode: "",
        },
        Occupation: {
          Educationalqualification: "",
          PresentOccupation: "",
          SourceofIncome: "",
          Nameofthepresentemployer: "",
          ExactNatureofduties: "",
          LengthofserviceYears: "",
          AnnualIncome: "",
          HaveyoueveremployedintheArmedForces: "",
          WingName: "",
          Ranktherein: "",
          Dateoflastmedicalexamination: "",
          MedicalCategory: "",
          WereyoueverbelowA1category: "",
          WhichYear: "",
        },
        PreviousPolicyDetails: [
          // {
          //   PolicyNumber: "",
          //   TypeofPolicy: "",
          //   NameoftheInsurer: "",
          //   Planname: "",
          //   Terminyears: "",
          //   Sumassured: "",
          //   TermRiderSumAssured: "",
          //   CIRiderSumAssured: "",
          //   ABADDBSumassured: "",
          //   DateofCommencement: "",
          //   DateofRevival: "",
          // },
        ],
      },
    ],
  };
}
export default PolicyJson;
