function PolicyJson() {
  return {
    PolicyStartDate: "",
    PolicyTerm: "",
    PremiumPayingTerm: "",
    PaymentFrequency: "",
    QuoteDate: "",
    QuoteNo: "",
    PolicyEndDate: "",
    Plan: "",
    ProductCode: "",
    SumAssured: "",
    RiskCount: "",
    ChildCount: "",
    PensionPeriod: "",
    LeadDetails: {},
    Channel: {
      BranchCode: "",
      BranchLocation: "",
      AgentID: "",
      AgentName: "",
      Salespersoncode: "",
      Salespersonname: "",
      ChannelType: "",
    },
    ProposerDetails: {
      CommunicationAddress: {
        AddressLine1: "",
        AddressLine2: "",
        AddressLine3: "",
        Landmark: "",
        City: "",
        District: "",
        State: "",
        Country: "",
        Pincode: "",
      },
      PermanentAddress: {
        AddressLine1: "",
        AddressLine2: "",
        AddressLine3: "",
        City: "",
        District: "",
        State: "",
        Country: "",
        Pincode: "",
      },
      ForeignAddress: {
        OCI: "",
        AddressLine1: "",
        AddressLine2: "",
        AddressLine3: "",
        City: "",
        District: "",
        State: "",
        Country: "",
        Pincode: "",
      },
      Name: "",
      FirstName: "",
      MiddleName: "",
      LastName: "",
      FatherName: "",
      MotherName: "",
      ContactNo: "",
      HomeNo: "",
      WorkNo: "",
      WhatsAppNo: "",
      Nationality: "",
      Salutation: "",
      EmailId: "",
      DOB: "",
      Age: "",
      Gender: "",
      MaritalStatus: "",
      OccupationCode: "",
      PanNo: "",
      AnnualIncome: "",
      GSTNumber: "",
      AadharCard: "",
      AlternateMobileNo: "",
      RelationWithInsured: "",
      RuralAndSocialSectorCategory: "",
      CKYCNo: "",
    },
    NomineeDetails: [
      //   {
      //     NomineeName: "",
      //     NomineeDOB: "",
      //     NomineeRelationWithProposer: "",
      //     PercentageOfShare: "",
      //     GuardianName: "",
      //     GuardianDOB: "",
      //     RelationshoipWithGuardian: "",
      //     RelationWithInsured: "",
      //     NomineeAddressLine1: "",
      //     NomineeAddressLine2: "",
      //     NomineeAddressLine3: "",
      //     NomineeMobile: "",
      //     NomineeEmailID: "",
      //     AppointeeName: "",
      //     NomineeCity: "",
      //     NomineeState: "",
      //     NomineePincode: "",
      //   },
    ],
    InsurableItem: [
      {
        InsurableName: "Person",
        Covers: [
          //   {
          //     CoverName: "",
          //     selected: true,
          //   },
        ],
        RiskItems: [
          {
            Name: "",
            DOB: "",
            Gender: "",
            RelationShip: "",
            Age: "",
            PassportNo: "",
            PreExistingDisease: "",
            SumAssured: "",
            RiderDetails: [
              //   {
              //     ProductRiderId: "",
              //     Ridername: "",
              //     SumAssured: "",
              //   },
            ],
            PremiumDetails: {
              CoverPremium: [{}],
              TaxDetails: [
                {
                  TaxType: "CGST",
                },
                {
                  TaxType: "SGST",
                },
                {
                  TaxType: "IGST",
                },
              ],
            },
            NomineeDetails: [
              //   {
              //     NomineeName: "",
              //     NomineeDOB: "",
              //     NomineeRelationWithProposer: "",
              //     PercentageOfShare: "",
              //     GuardianName: "",
              //     GuardianDOB: "",
              //     RelationshoipWithGuardian: "",
              //     RelationWithInsured: "",
              //     NomineeAddressLine1: "",
              //     NomineeAddressLine2: "",
              //     NomineeAddressLine3: "",
              //     NomineeMobile: "",
              //     NomineeEmailID: "",
              //     AppointeeName: "",
              //     NomineeCity: "",
              //     NomineeState: "",
              //     NomineePincode: "",
              //   },
            ],
            Questionnare: [
              {
                QId: "",
                Question:
                  "Heart disease like Heart attack, Heart failure, Ischemic heart disease or Coronary heart disease, Angina etc.",
                Answer: "No",
              },
              {
                QId: "",
                Question: "Tumor, Cancer of any organ, Leukemia, Lymphoma, Sarcoma",
                Answer: "No",
              },
            ],
            Occupation: {
              Educationalqualification: "",
              PresentOccupation: "",
              SourceofIncome: "",
              Nameofthepresentemployer: "",
              ExactNatureofduties: "",
              LengthofserviceYears: "",
              AnnualIncome: "",
              HaveyoueveremployedintheArmedForces: "",
              WingName: "",
              Ranktherein: "",
              Dateoflastmedicalexamination: "",
              MedicalCategory: "",
              WereyoueverbelowA1category: "",
              WhichYear: "",
            },
            PreviousPolicyDetails: [
              {
                PolicyNumber: "",
                TypeofPolicy: "",
                NameoftheInsurer: "",
                Planname: "",
                Terminyears: "",
                Sumassured: "",
                TermRiderSumAssured: "",
                CIRiderSumAssured: "",
                ABADDBSumassured: "",
                DateofCommencement: "",
                DateofRevival: "",
              },
            ],
          },
        ],
      },
    ],
    PremiumDetail: {
      CoverPremium: [{}],
      BasicPremium: "",
      Discount: "0",
      GrossPremium: "",
      TaxDetails: [
        {
          Amount: "",
          TaxType: "CGST",
        },
        {
          Amount: "",
          TaxType: "SGST",
        },
        {
          Amount: "",
          TaxType: "IGST",
        },
      ],
      TaxAmount: "",
      TotalPremium: "",
      InstallmentDetails: [{}],
    },
    PaymentDetails: {
      Payments: [
        // {
        //   TransactionNo: "",
        //   Amount: "",
        //   PaymentGateway: "",
        //   PaymentStatus: "",
        //   TransactionType: "",
        //   Description: "",
        //   ModeOfPayment: "",
        // },
      ],
      TransactionNo: "",
      Amount: "",
      PaymentGateway: "",
      PaymentStatus: "",
      EmailId: "",
      TransactionType: "",
      Description: "",
      ModeOfPayment: "",
      DocumentType: "",
    },
    DocumentDetails: [
      //   {
      //     DocumentType: "",
      //     DocumentId: "",
      //     DocumentName: "",
      //     ContentType: "",
      //   },
    ],
    BankDetails: {
      TypeofAccount: "",
      AccountNo: "",
      MICRCode: "",
      IFSCode: "",
      Nameofyourbank: "",
      Addressofyourbank: "",
    },
  };
}
export default PolicyJson;
