const ClaimsDetails = () => {
  const dto = {
    claimsMenuId: 0,
    claimId: 0,
    Prefix: "",
    NumberType: "",
    AttributeName: "",
    ClaimNumber: "",
    claimStatusId: 0,
    claimStatus: "",
    claimAmount: 0,
    claimManagerRemarks: "",
    approvedClaimAmount: 0,
    createdDate: "",
    createdBy: "",
    lossDateTime: "",
    locationOfEvent: "",
    lossOfDescription: "",
    policyId: 0,
    active: true,
    modifiedBy: "",
    modifiedDate: "",
    partnerId: 0,
    organizationId: 0,
    ProductCode: "NepalMotorTwoWheeler",
    policyNo: "",
    doc: "",
    productIdPk: 1193,
    claimFields: "",
    company: "",
    lob: "",
    claimBasicDetails: {
      productCode: "NepalMotorTwoWheeler",
      PolicyDetails: {
        ParticipantName: "",
        productType: "",
        PolicyNo: "",
        VehiclePlateNo: "",
        VehicleUsageType: "",
        ChassisNumber: "",
        PolicyStartDate: "",
        EngineNumber: "",
        MobileNumber: "",
        Coverages: "",
        PolicyEndDate: "",
        isPolicyDetailsVerified: true,
        iscommunicationMbEm: true,
        isIntimated: "",
        EmailId: "",
        PolicyNumber: "",
      },
      Channel: {},
      ProposerDetails: {},
      NomineeDetails: [{}],
      ClaimPaymentDetails: [{}],
      FinancierDetails: {},
    },
    transactionDataDTO: [
      {
        transactionDetails: {
          TransactionFlag: "",
          ProductCode: "",
          NumberType: "",
          Prefix: "INT",
          AttributeName: "",
          TransactionType: "",
          TransactionNo: "",
          TreatyType: "",
          RIDetails: {
            RIEmail: "",
          },
          CoverDetails: {},
          ClaimsInfo: {
            IntimationDetails: {
              isAnyWitness: "",
              IntimationMode: "",
              AccidentLocation: "",
              otherAccidentLocation: "",
              AccidentDate: "",
              causeofAccident: "",
              AccidentRemarks: "",
              NotifiedBy: "",
              wasVehicleParked: "",
              DriverName: "",
              DriverAge: "",
              DrivingLicenseNo: "",
              Gender: "",
              DriverMobileNo: "",
              DLCategory: "",
              Nationality: "",
              isROPReported: "",
              ROPNo: "",
              ROPReportDate: "",
              ROPOfficerName: "",
              ROPLocation: "",
            },
            ProcessingDetails: {
              wasVehicleParked: "",
              DriverName: "",
              DriverAge: "",
              DrivingLicenseNo: "",
              Gender: "",
              DriverMobileNo: "",
              DLCategory: "",
              Nationality: "",
              isROPReported: "",
              ROPNo: "",
              ROPReportDate: "",
              ROPOfficerName: "",
              ROPLocation: "",
            },
            AdvancePayment: {
              PayeeName: "",
              ReasonForAdvancePayment: "",
              TotalAmountinAdvance: "",
              ModeofPayment: "",
              BankAccNo: "",
              BalanceTotalPayable: "",
            },
            InsurableItem: [
              {
                InsurableName: "",
                RiskItems: [
                  {
                    isInsured: "",
                    needtowingservices: "",
                    VehiclereplacementCoverage: "",
                    MobileNo: "",
                    otherLocation: "",
                    otherWorkShop: "",
                    isTPVehicleDamaged: "",
                    Gender: "",
                    Make: "",
                    otherMake: "",
                    Model: "",
                    otherModel: "",
                    vehicleType: "",
                    mulkiyaExpiryDate: "",
                    TPAge: "",
                    VehiclePlateNo: "",
                    isAmbulanceServiceAvailed: "",
                    isTPPropertyDamaged: "",
                    PropertyType: "",
                    PropertyDescription: "",
                    otherpropertyDescription: "",
                    Wilayat: "",
                    OtherWilayat: "",
                    Claimshandler: "",
                    Relationwithparticipant: "",
                    otherRelationwithparticipant: "",
                    isInjurySelfOrTP: "",
                    InjuryType: "",
                    IsDeseasedAccident: "",
                    IsAnimalDeathOrInjury: "",
                    TypeofAnimal: "",
                    OtherTypeofAnimal: "",
                    Typeofloss: "",
                    Count: "",
                  },
                ],
              },
            ],
            claimDetails: {
              businessType: "",
              insuredName: "",
              branch: "",
              subBranch: "",
              intimationBranch: "",
              claimFiscalYear: "",
              registerDate: "",
              dateOfLoss: "",
              intimationDate: "",
              claimFormDate: "",
              claimCause: "",
              transportationReg: "",
              affectedProperty: "",
              natureOfLoss: "",
              claimant: "",
              comments: "",
              EmailId: "",
              contactPersonName: "",
              mobileNumber: "",
              ownVehicleNumber: "",
              tpVehicleNumber: "",
              Remarks: "",
              riskCovered: "",
              trasportRegisterOffice: "",
            },
            placeofOccurance: {
              country: "Nepal",

              province: "",
              provinceId: "",
              district: "",
              districtId: "",
              municipality: "",
              wardNumber: "",
              Address: "",
              AddressNepali: "",
              Area: "",
              Tole: "",
              HouseNumber: "",
              plotNumber: "",
            },
            LossInformation: {
              lossType: "",
              subLossType: "",
              materialType: "",
              particulars: "",
              sumInsured: "",
              claimAmount: "",
            },
          },
          SurveyorDetails: {
            surveyorType: "",
            surveyType: "",
            surveyorName: "",
            surveyorStaff: "",
            mobileNumber: "",
            surveyorEmail: "",
            surveyorDeputedDate: "",
            placeOfSurvey: "",
            reportSubmissionWithin: "",
            SurveyorApplicable: "",
            isReportSubmission: "",
            isClaimDenied: "",
            reportSubmissionDate: "",
            reportNumber: "",
            inHouseUser: "",
            remarks: "",
            estimatedAmount: "",
            ApprovedDate: "",
            ApprovalAuthority: "",
            SurveyorDocumentCount: "",
            surveyorFeeDetails: {
              surveyorFee: "",
              surveyorTDSPercent: "",
              surveyorVATPercent: "",
              surveyorTDS: "",
              surveyorVAT: "",
              otherFee: "",
              otherFeeTaxable: "",
              otherFeeTDSPercent: "",
              otherFeeVATPercent: "",
              otherFeeTDS: "",
              otherFeeVAT: "",
              totalSurveyFee: "",
              totalSurveyFeeVAT: "",
              sFeePayable: "",
              estimatedLoss: "",
              totalLoss: "",
              remarks: "",
            },
            SurveyorReport: [
              {
                docId: "",
                fileName: "",
                docName: "",
                UploadDateTime: "",
              },
            ],
            AssessmentDetails: [{}],
          },
          claimApproval: {
            salvagerecovery: "",
            riApprovalStatus: "",
            riApprovedby: "",
            approvedLimit: "",
            approvedDate: "",
            approvedAuthority: "",
            remarks: "",
            nepalRI: "",
            slNo: "",
            recommendedBy: "",
            recommendedDate: "",
            remark: "",
            includeSurveyorFee: "",
          },
          Temp: {
            Discharge: [],
          },
          DischargeVoucher: {
            DVType: "",
            DVChangeDate: "",
            Remark: "",
            DVStatus: "",
            PayTo: "",
            ClaimantAddress: "",
            KYCNumber: "",
            AccAddress: "",
            AccNameNepali: "",
            PANNumber: "",
            MobileNumber: "",
            ContactNumber: "",
            CitizenshipNumber: "",
            Amount: "",
            AccNumber: "",
            AccHolderName: "",
            BankName: "",
            BranchName: "",
            NepalDV: "",
            SubrogrationLetter: "",
            DVfromCustomer: "",
            Documents: {
              docId: "",
              fileName: "",
              docName: "",
              uploadDateTime: "",
            },
          },
          AssessmentSummary: [
            {
              Type: "",
              TotalAmount: "",
            },
          ],
          InvoiceDetails: [{}],
          WorkshopDetails: [
            {
              ClaimsHandler: "",
              Location: "",
              WorkShop: "",
              otherLocation: "",
              otherWorkShop: "",
            },
          ],
          Remarks: [
            {
              Note: "",
              Documents: [],
            },
          ],
          HospitalDetails: [{}],
          ServiceProvider: [{}],
          documentDetails: [],
          TPADetails: [{}],
          EmployeeDetails: {},
          CourierDetails: [{}],
          BillingDetails: [{}],
          WorkOrderDetails: [
            {
              Type: "",
            },
          ],
          ClaimAmountDetails: {},
          ActualPaymentDetails: [
            {
              PaidTo: "",
            },
          ],
          AuditDetails: [{}],
          WFDetails: {},
          WfId: "",
          WFHistory: [
            {
              StatusChangeandRemarks: "",
            },
          ],
          ReInsuranceReserveDetails: "",
          TotalAmount: "",
          ReserverHistory: [{}],
          BRETriggerDetails: [
            {
              TriggerEvent: "",
              BREDetails: [{}],
            },
          ],
          ClaimPaymentDetails: {
            Total: [
              {
                Type: "",
                TotalAmount: "",
              },
            ],
          },
        },
        transactionId: 0,
        isValid: "",
        createdDateTime: "",
        modifiedDateTime: "",
        createdBy: "",
        modifiedBy: "",
        occurrence: "",
        claimId: 0,
        statusId: 0,
        claimTypeId: 0,
        claimServiceTypeId: 0,
        causeOfLossId: 0,
        actionId: 0,
        isServeyorAssign: "",
        isWorkshopAssign: "",
        isInvestigatorAssign: "",
        isBackByManager: "",
        isReOpen: "",
        isRoadSideAssistance: "",
        approximateEstimatedCost: "",
        remark: "",
        internalRemark: "",
        emergencyContact: "",
        emergencyEmail: "",
        queryReasonIds: "",
        rejectionReasonIds: "",
        accidentFactor: "",
        accidentFactorDescription: "",
        isRead: "",
        approvedAmount: 0,
        decisionTypeid: 0,
        settlementTypeid: 0,
        closeReasonIds: "",
        isPriorityClaim: "",
        reopenReasonIds: "",
        advanceAmount: 0,
        claimNo: "",
        workItemNo: "",
        workItemId: 0,
        userName: "",
        transactionNumber: "",
        transactionStageStatusId: 0,
        transactionStageId: 0,
        isActive: "",
        ReferenceNo: 1,
        IntimatedDate: "",
      },
    ],
    RIApproval: {
      FiscalYear: "",
      ApprovedDate: "",
    },
  };
  return dto;
};

export default ClaimsDetails;
