const data = {
  "Policy Tenure": 0,
  "Building Structure Value": "500000",
  "Building Content Value": "50000",
  "Personal Accident Cover (Death Only) - Optional": "Yes",
  "Terrorism Cover - Optional": "No",
  "Cover for Valuable Contents - Optional": "Yes",
  "Policy End Date": "Fri Aug 25 2023",
  "Policy Start Date": "Thu Aug 25 2022",
  ProposalData: {
    Salutation: 172,
    Name: "Ravichandran M",
    "Date of Birth": "Thu Jul 13 1995",
    Gender: 1749,
    "Mobile Number": "9304582748",
    "Email ID": "ravi@inubesolutions.com",
    termscondition: true,
    autoFill: false,
    Age: 27,
    PinCode: "560078",
    Area: 154599,
    District: 65,
    State: 17,
    EnhancedSumAssured: "",
    NomineeRelation: 153,
    NomineeName: "hvjgv",
    SumInsured: "",
    Address: "JPN",
    "Policy Tenure": 0,
    OtherRelation: "",
    ProductId: "",
    undefined: false,
  },
  "Product Code": "BharatGrihaRaksha1",
  PremiumData: {
    "Sum Insured": 0,
    "Base Premium": 0,
    "Terrorism Base": 0,
    "Loss (Premium)": 0,
    "Loss(Terrorism)": 0,
    "Long term": 0,
    "Net Premium": 0,
    "Disc/Loading %": 0,
    "Prem aft Disc": 0,
    "Terrorism Prem": 0,
    "Total Premium": 0,
    SGST: 0,
    CGST: 0,
    "Total with Tax": 0,
  },
  permiumamount: "550",
  InsurableItem: [
    {
      InsurableName: "Person",
      RiskItems: [{}],
      Covers: [{ CoverName: "Home Building Cover", CoverFields: [{}] }],
    },
  ],
  "Reference No": "8633604f-8704-4a93-8105-f8dbad952544",
  Razorpay_Payment_ID: "pay_K9liKP2AuNvLdp",
};
export default data;
