const data = {
  TransactionID: "",
  // ProposalNo: "",
  SubProduct: "",
  CkycStatus: "",
  CkycDetails: {},
  ProductName: "BHARAT GRIHA RAKSHA",
  GCProductCode: "2123",
  GCProductName: "UNIVERSAL SOMPO - BHARAT GRIHA RAKSHA",
  "Agent Id": "",
  ProposerDetails: {
    CKYCParam: "",
    AadharMobileNo: "",
    AadharName: "",
    AadharGender: "",
    CommunicationSameAsPermanent: "No",
    CustomerId: "",
    "Customer Type": "Individual",
    Salutation: "",
    "First Name": "",
    "Last Name": "",
    Name: "",
    "Mobile Number": "",
    "Email ID": "",
    "Date of Birth": "",
    termscondition: true,
    autoFill: "",
    Age: "",
    PinCode: "",
    Area: "",
    District: "",
    State: "",
    EnhancedSumAssured: "",
    "Nominee Date of Birth": "",
    "Nominee First Name": "",
    "Nominee Last Name": "",
    "Appointee Name": "",
    RelationshipwithNominee: "",
    Relationshipwithproposer: "",
    NomineeGender: "",
    NomineeTitle: "",
    NomineeAge: "",
    "Is Nominee a Minor?": "No",
    SumInsured: "",
    Address1: "",
    Address2: "",
    NearestLandmark: "",
    RiskLocationAddress: {
      Address1: "",
      Address2: "",
      NearestLandmark: "",
      Country: "India",
      PinCode: "",
      State: "",
      District: "",
      Statecode: "",
      Districtcode: "",
      PlotNo: "",
    },
    CommunicationAddress: {
      Address1: "",
      Address2: "",
      NearestLandmark: "",
      Country: "India",
      PinCode: "",
      State: "",
      District: "",
      Statecode: "",
      Districtcode: "",
      PlotNo: "",
    },
    PermanentAddress: {
      Address1: "",
      Address2: "",
      NearestLandmark: "",
      Country: "India",
      PinCode: "",
      PlotNo: "",
      District: "",
      State: "",
      Statecode: "",
      Districtcode: "",
    },
    "Policy Tenure": 0,
    "Policy End Date": "",
    "Policy Start Date": "",
    OtherRelation: "",
    ProductId: "",
    undefined: false,
    "GST Number": "",
    "PAN Number": "",
    "CIN Number": "",
    AadharID: "",
    IsHomeOwned: "",
  },
  QuoteMobileNo: "",
  QuoteEmail: "",
  "Product Code": "BGRUSGI02",
  permiumamount: "",
  InsurableItem: [
    {
      InsurableName: "Building",
      RiskItems: [
        {
          "Carpet Area (in sq. fts.)": "",
          "Do You want to take Personal Accident Cover?": "No",
          "Personal Accident Sum Insured": "",
          "Insured Members Covered under Individual PA?": "",
          "Loss Of Rent(Months)": "",
          "Value of Inbuilt content (excluding valuable)": "",
          "Rent for Alternative Accommodation(Months)": "",
          "Do you want to cover loss of rent ?": "No",
          "Do you want to cover Rent for Alternative Accommodation ?": "No",
          "Additional Parameter": "No",
          "Carpet Area (in sq. mts.)": "",
          "Cost of Construction": "",
          "Type of Construction": "",
          "Year of Construction": "",
          "Age of Building": "",
          "Type of Building": "",
          "Residential Structure Sum Insured": "",
          "Type of Rent Cover": "",
          "Rent Per Month": "",
          "No. of months": "",
          "Occupying the premises as": "",
          Housekeeping: "",
          "Rent Covered Sum Insured": "",
          "Past Claims Experience of the Risk(%)": "",
          "Do you want to cover additional structure?": "",
          "Additional Structure SI": "",
          "Are you a USGI Employee?": "No",
          "Total Building SI": "",
          "Year of Construction(Age of Building)": "",
          "Cost of Construction per Sqft": "",
          "Carpet Area per Sqft": "",
          "Total cost of construction/Sum Insured": "",
          "Does the Building have a basement ?": "No",
          "Risk Terrain": "",
          "Insured Members Covered Under Individual PA": "",
          "Electric & Electronic Items Sum Insured": "",
          "Other Sum Insured": "",
          "Furniture, Fixture & Fittings Sum Insured": "",
          "TotalCostofContents/SumInsured": "",
          Loading: "",
          TerrorismCover: "No",
        },
      ],
      Covers: [
        {
          CoverName: "Griha Raksha",
          CoverFields: [{}],
        },
      ],
    },
  ],
  OtherDetails: [
    {
      FinancierInterest: [
        {
          IsHomeOwned: "No",
          "Select Finance Type": "",
          "Financier Company Name": "",
          "Please enter company address": "",
          "Loan Account Number": "",
          "Branch of the Financial Institution": "",
        },
      ],
      EissuanceandOtherDetails: [
        {
          "Do you want to open a new account?": "",
          "Please enter your E-Insurance Account Number": "",
          "Do you have e Insurance Account number?": "",
          "GSTIN Number": "",
          "TIN Number": "",
          "Other Information1": "",
          "Other Information2": "",
        },
      ],
    },
  ],
  "Business Type": "New Business",
  "Customer Category": "",
  "Proposal Type": "",
  "Customer Type": "",
  "Policy Tenure": "",
  "Cover Type": "",
  "Branch Name": "",
  "Cover Type ( What do you need to insure)": "",
  "Co-operative Housing Societies details": "",
  "Occupying the premises": "",
  "Communication Address State/Property’s State": "",
  "Select Occupancy Type": "",
  Plan: "",
  PremiumDetails: {
    "Sum Insured": "",
    "Base Premium": "",
    "Terrorism Base": "",
    "Add On (Premium)": "",
    "Rent for Accomodation (Premium)": "",
    "Loss(Terrorism)": "",
    "Long term": "",
    "Net Premium": "",
    "Disc/Loading %": "",
    "Prem aft Disc": "",
    "Terrorism Premium": "",
    "Premium Excluding Terrorism": "",
    "Total Fire Premium": "",
    "Total STFI Premium": "",
    "Total EQ Premium": "",
    "Total Premium": "",
    SGST: "",
    CGST: "",
    "Total with Tax": "",
    BuildingFireRate: "",
    BuildingSTFIRate: "",
    ContentFireRate: "",
    TotalFireRate: "",
    TotalSTFIRate: "",
    BuildingEQRate: "",
    ContentSTFIRate: "",
    ContentEQRate: "",
    TotalEQRate: "",
    TerrorismRate: "",
    TotalBaseRate: "",
    EQExcTerrPremium: "",
    STFIExcTerrPremium: "",
    FireExcTerrPremium: "",
    GCLoadingBasePremiumBGR: "",
    PAPremium: "",
    NewBuildingPremium: "",
    BuildingFirePremium: "",
    BuildingSTFIPremium: "",
    BuildingEQPremium: "",
    NewContentPremium: "",
    ContentFirePremium: "",
    ContentSTFIPremium: "",
    ContentEQPremium: "",
  },
  PaymentDetails: {
    ChequeAmount: "",
    InstrumentNo: "",
    InstrumentDate: "",
    BankName: "",
    transactionNo: "",
    paymentSource: "",
    paymentId: "",
    paymentResponse: "",
    paymentType: "Agent Payment",
  },
  Razorpay_Payment_ID: "",
  Channel: {
    BranchCode: "",
    BranchLocation: "",
    AgentID: "",
    AgentName: "",
    AgentType: "",
    AgentContactNo: "",
    Salespersoncode: "",
    Salespersonname: "",
    ChannelType: "Agency",
    OfficeCode: "",
    OfficeName: "",
    OfficeAddress: "",
    PrimaryMOCode: "",
    PrimaryMOName: "",
    PrimaryVerticalCode: "",
    PrimaryVerticalName: "",
    DealId: "",
  },
  // Channel: {

  //   BranchCode: "NA",
  //   BranchLocation: "MUMBAI CORPORATE OFFICE",
  //   AgentID: "201670975657",
  //   AgentName: "POLICY BAZAAR INSURANCE WEB AGGREGATOR PVT LTD",
  //   AgentContactNo: "7977473633",
  //   Salespersoncode: "201670975657",
  //   Salespersonname: "POLICY BAZAAR INSURANCE WEB AGGREGATOR PVT LTD",
  //   ChannelType: "Agency",
  //   OfficeAddress:
  //     "MORADABAD BRANCH SF211A,SECOND FLOOR, SF 211A, SECOND FLOOR, PARSVNATH PLAZA I, DELHI ROAD,MORADABAD 244001, UTTAR PRADESH (09) GSTIN - 09AAACU8917F1Z4",
  // },
  PremiumDetail: {
    PremiumBreakup: {
      SumInsured: "",
      TerrorismBase: "",
      LossPremium: "",
      LossTerrorism: "",
      Longterm: "",
      NetPremium: "",
      DiscLoading: "",
      TerrorismPrem: "",
    },
    BasicPremium: "",
    Discount: "",
    GrossPremium: "",
    TaxDetails: [
      {
        Amount: "",
        TaxType: "CGST",
      },
      {
        Amount: "",
        TaxType: "SGST",
      },
      {
        Amount: "",
        TaxType: "IGST",
      },
    ],
    TaxAmount: "",
    TotalPremium: "",
  },
  LOB: "Fire",
  propNo: "",
};

export default data;
